name: notus_format
description: Platform-agnostic rich text document model based on Delta format and used in Zefyrka editor.
version: 1.0.3
homepage: https://github.com/glynskyi/notus_format

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: ^1.18.0
  quiver: ^3.2.1
#  quill_format: ^1.0.2
  quill_format:
    git:
      url: https://github.com/tony-soft/quill_format.git
      ref: 621f198f265c5f5e798bd853e90c875d765a80c4

dev_dependencies:
  coverage: ^1.7.2
  pedantic: ^1.11.1
  test: ^1.25.2
